- hosts: all
  become: true
  roles:
    - role: preparing-server-role
      tags:
        - preparing
    - role: containerd-install-role
      tags:
        - containerd
    - role: docker-install-role
      tags:
        - docker