networks:
  web_net:
    external: true
    name: web_net

services:
  hiddify:
    image: repo.tavakolzadeh.ir:8082/handei/hiddify
    container_name: hiddify
    hostname: ${HOSTNAME}
    restart: ${RESTART_POLICY}
    volumes:
      - ./config.json:/etc/hiddify/hiddify.json
    privileged: true
    networks:
      - web_net
    environment:
      - TZ=Asia/Tehran
