networks:
  vpn_net:
    external: true
    name: vpn_net
  # app_net:
  #   external: true
  #   name: app_net



services:
  hiddify:
    image: repo.tavakolzadeh.ir:8082/handei/hiddify
    container_name: hiddify
    hostname: ${HOSTNAME}
    restart: ${RESTART_POLICY}
    volumes:
      - ./config.json:/etc/hiddify/hiddify.json
    # networks:
    #   - web_net
    privileged: true
    networks:
      - vpn_net
    environment:
      - TZ=Asia/Tehran
    ports:
      - 3334:2334
      - 3335:2335
      - 7756:6756
      - 7450:6450
