services:
  gitlab-runner:
      image: repo.tavakolzadeh.ir:8082/gitlab/gitlab-runner:latest
      restart: always
      container_name: gitlab-runner
      hostname: gitlab-runner
      volumes:
       - ./config:/etc/gitlab-runner
       - /var/run/docker.sock:/var/run/docker.sock
      networks:
       - web_net
      extra_hosts:  # set hostname traefik for loadbalance
        - "git.tavakolzadeh.ir:172.20.0.2"
        - "kube-api.tavakolzadeh.ir:192.168.56.10"
        - "registry.tavakolzadeh.ir:172.20.0.2"

networks:
   web_net:
     name: web_net
     external: true
