---
# vars file for docker
- name: Uninstall old versions
  apt: 
    name: "{{ item }}"
    state: absent
    purge: yes
  loop: [docker-doc, docker.io, docker-compose, docker-compose-v2, podman-docker, containerd, run, docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin, docker-ce-rootless-extras]
  
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - software-properties-common
    - apt-transport-https

- name: Add Docker GPG key with proxy
  shell: sudo curl --proxy 192.168.1.4:2334 -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  become: yes

- name: Get architecture
  command: dpkg --print-architecture
  register: architecture


- name: Add a line to a file docker.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [trusted=true arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] http://repo.tavakolzadeh.ir/repository/docker-apt/ {{ ansible_distribution_release }} stable"
    create: yes

- name: Install a list of packages
  ansible.builtin.apt:
    force_apt_get: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify:
    reload docker

#Manage non-root access
- name: Add docker group
  group:
    name: docker
    state: present

- name: get username
  command: whoami
  become: false
  register: USER

- name: Add user to docker group
  user:
    name: "{{ USER.stdout}}"
    groups: docker
    append: true
