global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_auth_identity: ''

route:
  receiver: 'Production_Environment'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  group_by: ['instance', 'severity']

receivers:
  - name: 'Production_Environment'
    email_configs:
      - to: ''
        send_resolved: true
